# Gemfile for L2RR2L iOS App

source "https://rubygems.org"

gem "fastlane", "~> 2.220"
gem "cocoapods", "~> 1.14"

# Fastlane plugins
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
