# Gemfile - Ruby dependencies for fastlane
#
# Install with: bundle install
# Update with: bundle update

source "https://rubygems.org"

# Fastlane - iOS deployment automation
gem "fastlane", "~> 2.219"

# Plugins
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
